#!/bin/bash
#####################################################
# Author: Dan Allen	
# Purpose:
# 	Automated configuration of LAMP
#	
# 
# Notes:
#	run with sudo	
#	
######################################################



# clean up yum
yum clean all
yum -y update

# install apache
yum -y install httpd

# allow apache through firewall
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload

# configure apache to start on boot
systemctl start httpd
systemctl enable httpd
systemctl status httpd

# if you want to stop apache
#systemctl stop httpd

# SSL setup
# probably not necessary for now...
yum -y install mod_ssl


# install mysql
yum -y install mariadb-server mariadb
systemctl start mariadb
mysql_secure_installation
#start on boot
systemctl enable mariadb.service

# install php
yum -y install php php-mysql
## TODO: may need to add some php modules

# install git
yum -y install git