#!/bin/bash
#####################################################
# Author: Dan Allen	
# Purpose:
# 	Automated configuration of LAMP
#	
# 
# Notes:
#	run with sudo	
#	
######################################################



# clean up yum
yum clean all
yum -y update

# install apache
yum -y install httpd

# allow apache through firewall
firewall-cmd --permanent --add-port=80/tcp
firewall-cmd --permanent --add-port=443/tcp
firewall-cmd --reload

# configure apache to start on boot
systemctl start httpd
systemctl enable httpd
systemctl status httpd

# if you want to stop apache
#systemctl stop httpd

# SSL setup
# probably not necessary for now...
yum -y install mod_ssl


# install mysql
yum -y install mariadb-server mariadb
systemctl start mariadb
mysql_secure_installation
#start on boot
systemctl enable mariadb.service


# install php
yum -y install php php-mysql
## TODO: may need to add some php modules

# install git
yum -y install git

# clone repo
cd /var/www/
git clone https://github.com/danrlyon/soh-app.git

#Change /etc/httpd/conf/httpd.conf/htt
# ^Keep as default to make it simple

# Moving the mySQL Data directory
# NOT WORKING!!
#systemctl stop mariadb
#systemctl status mariadb
#rsync -av /var/lib/mysql /var/www/html/db
#cp -a /var/lib/mysql /var/lib/mysqlBak
# Pointing to the new data location
# must already have git repo pulled since my.cnf is stored there
#unalias cp
#cp -afv /var/www/html/db/dbconf/my.cnf /etc/my.cnf
#cp -afrv /var/www/html/db/dbconf/my.cnf.d /etc

# Install PHP package manager PEAR
yum install wget
wget http://pear.php.net/go-pear.phar
# Install ssh2
yum install gcc php-devel php-pear libssh2 libssh2-devel make
pecl install -f ssh2
echo extension=ssh2.so > /etc/php.d/ssh2.ini
service httpd restart
php -m | grep ssh2

# Add portion to configure cron table








