#!/bin/sh

# HEAL
# Parse NAN from July, 2017

# List EEPROM IDs to check
SWC1=42344
SWC2=42345
SWC3=42346
SWC4=42347
SWC5=42348
DATAPATH=/opt/neon/data/sockets_201707
RESULTSPATH=/opt/neon/bin/Test/SWC+NAN/results/July2017_

# Check each sensor and output a file
CURRENT=$SWC1
echo "Checking for NAN where EEPROM id=${CURRENT}."
vd -s $CURRENT -f ${DATAPATH} | grep NAN > ${RESULTSPATH}${CURRENT}.csv

CURRENT=$SWC2
echo "Checking for NAN where EEPROM id=${CURRENT}."
vd -s $CURRENT -f ${DATAPATH} | grep NAN > ${RESULTSPATH}${CURRENT}.csv

CURRENT=$SWC3
echo "Checking for NAN where EEPROM id=${CURRENT}."
vd -s $CURRENT -f ${DATAPATH} | grep NAN > ${RESULTSPATH}${CURRENT}.csv

CURRENT=$SWC4
echo "Checking for NAN where EEPROM id=${CURRENT}."
vd -s $CURRENT -f ${DATAPATH} | grep NAN > ${RESULTSPATH}${CURRENT}.csv

CURRENT=$SWC5
echo "Checking for NAN where EEPROM id=${CURRENT}."
vd -s $CURRENT -f ${DATAPATH} | grep NAN > ${RESULTSPATH}${CURRENT}.csv